version: 2

updates:
  - package-ecosystem: gomod
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /apps/admin
    schedule:
      interval: weekly
    groups:
      admin-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/admin
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
