baseURL = "http://localhost:1313/"
locale                 = "zh-cn"
title = "Zoking 博客"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = true
enableRobotsTXT        = true
disableLanguages       = ["en", "zh-hant-tw", "ja"]

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[pagination]
    pagerSize = 6

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
